before_install:
- "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-full texlive-fonts-extra texlive-latex-recommended dvipng"
script:
- xelatex main.tex
deploy:
  provider: releases
  file:
  - main.pdf
  skip_cleanup: true
  on:
    tags: true
